language: python

python:
    - "3.5"

addons:
  postgresql: "9.5"

services:
  - postgresql

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt

before_script:
    - uname -a
    - printenv
    - pip list
    - psql -c 'create database bookdb;' -U postgres


script:
    - date
    - ls -al
    - make check
    - make test

notifications:
    slack: cs329e-imdb:zvmrI15PtkbYfF6Lc599CQvG