runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app
install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt

runtime_config:
  python_version: 3
